-- MySQL Script generated by MySQL Workbench
-- Fri Oct 30 14:36:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cosc457
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cosc457
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cosc457` DEFAULT CHARACTER SET utf8 ;
USE `cosc457` ;

-- -----------------------------------------------------
-- Table `cosc457`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`department` (
  `department_id` INT(96) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `advisor` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `idtable1_UNIQUE` (`department_id` ASC) VISIBLE,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`issued_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`issued_id` (
  `id` INT(96) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `middle_init` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `phone_number_home` VARCHAR(50) NULL,
  `phone_number_work` VARCHAR(50) NULL,
  `birth_date` VARCHAR(50) NOT NULL,
  `id_creation_date` DATE NOT NULL,
  `id_expiration_date` DATE NULL,
  `gender` VARCHAR(50) NOT NULL,
  `grant_status` VARCHAR(50) NULL,
  `citizenship_status` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL,
  `social_security_number` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `department_id` INT(96) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `social_security_number_UNIQUE` (`social_security_number` ASC) VISIBLE,
  INDEX `fk_issued_id_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_issued_id_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `cosc457`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`completed_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`completed_courses` (
  `completed_course_id` INT(96) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `grade` VARCHAR(50) NOT NULL,
  `offering_department` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `semester_title` VARCHAR(50) NOT NULL,
  `issued_id` INT(96) NOT NULL,
  PRIMARY KEY (`completed_course_id`),
  UNIQUE INDEX `course_uuid_UNIQUE` (`completed_course_id` ASC) VISIBLE,
  INDEX `fk_completed_courses_issued_id1_idx` (`issued_id` ASC) VISIBLE,
  CONSTRAINT `fk_completed_courses_issued_id1`
    FOREIGN KEY (`issued_id`)
    REFERENCES `cosc457`.`issued_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`offered_programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`offered_programs` (
  `program_id` INT(96) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `department_id` INT(96) NOT NULL,
  PRIMARY KEY (`program_id`),
  UNIQUE INDEX `course_uuid_UNIQUE` (`program_id` ASC) VISIBLE,
  INDEX `fk_offered_programs_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_offered_programs_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `cosc457`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`offered_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`offered_courses` (
  `offered_course_id` INT(96) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `description` VARCHAR(1024) NULL,
  `semester_title` VARCHAR(45) NOT NULL,
  `issued_id` INT(96) NOT NULL,
  `program_id` INT(96) NULL,
  `department_id` INT(96) NOT NULL,
  PRIMARY KEY (`offered_course_id`),
  UNIQUE INDEX `course_uuid_UNIQUE` (`offered_course_id` ASC) VISIBLE,
  INDEX `fk_offered_courses_issued_id1_idx` (`issued_id` ASC) VISIBLE,
  INDEX `fk_offered_courses_offered_programs1_idx` (`program_id` ASC) VISIBLE,
  INDEX `fk_offered_courses_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_offered_courses_issued_id1`
    FOREIGN KEY (`issued_id`)
    REFERENCES `cosc457`.`issued_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offered_courses_offered_programs1`
    FOREIGN KEY (`program_id`)
    REFERENCES `cosc457`.`offered_programs` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offered_courses_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `cosc457`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`visits` (
  `visit_id` INT(96) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `issued_id` INT(96) NOT NULL,
  PRIMARY KEY (`visit_id`),
  UNIQUE INDEX `course_uuid_UNIQUE` (`visit_id` ASC) VISIBLE,
  INDEX `fk_visits_issued_id1_idx` (`issued_id` ASC) VISIBLE,
  CONSTRAINT `fk_visits_issued_id1`
    FOREIGN KEY (`issued_id`)
    REFERENCES `cosc457`.`issued_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`address` (
  `address_id` INT(96) NOT NULL AUTO_INCREMENT,
  `is_permanent_residence` TINYINT NULL,
  `is_current_residence` TINYINT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `middle_init` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `issued_id` INT(96) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postalcode` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `address_uuid_UNIQUE` (`address_id` ASC) VISIBLE,
  INDEX `fk_address_student1_idx` (`issued_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_student1`
    FOREIGN KEY (`issued_id`)
    REFERENCES `cosc457`.`issued_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`advises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`advises` (
  `advise_id` INT(96) NOT NULL,
  `issued_id` INT(96) NOT NULL,
  `student_id` INT(96) NOT NULL,
  PRIMARY KEY (`advise_id`),
  UNIQUE INDEX `course_uuid_UNIQUE` (`advise_id` ASC) VISIBLE,
  INDEX `fk_advises_issued_id1_idx` (`issued_id` ASC) VISIBLE,
  CONSTRAINT `fk_advises_issued_id10`
    FOREIGN KEY (`issued_id`)
    REFERENCES `cosc457`.`issued_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosc457`.`enrolled_programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`enrolled_programs` (
  `completed_program_id` INT(96) NOT NULL AUTO_INCREMENT,
  `program_id` INT(96) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `is_completed` TINYINT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `issued_id` INT(96) NOT NULL,
  PRIMARY KEY (`completed_program_id`),
  UNIQUE INDEX `course_uuid_UNIQUE` (`completed_program_id` ASC) VISIBLE,
  INDEX `fk_enrolled_programs_issued_id1_idx` (`issued_id` ASC) VISIBLE,
  CONSTRAINT `fk_enrolled_programs_issued_id1`
    FOREIGN KEY (`issued_id`)
    REFERENCES `cosc457`.`issued_id` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
