-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 10:38:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cosc457
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cosc457
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cosc457` DEFAULT CHARACTER SET utf8 ;
USE `cosc457` ;

-- -----------------------------------------------------
-- Table `cosc457`.`Id_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Id_christian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_issued` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_expired` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'active',
  `fname` VARCHAR(45) NOT NULL,
  `mname` VARCHAR(45) NULL DEFAULT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `dob` DATE NOT NULL,
  `street` VARCHAR(45) NOT NULL DEFAULT '2901 Liberty Heights Avenue',
  `city` VARCHAR(45) NOT NULL DEFAULT 'Baltimore',
  `zip` VARCHAR(5) NOT NULL DEFAULT '21215',
  `state` VARCHAR(2) NOT NULL DEFAULT 'MD',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8
COMMENT = 'status: \'active\', \'expired\', \'visitor\' (where visitor expires in just a few days max)';


-- -----------------------------------------------------
-- Table `cosc457`.`Staff_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Staff_christian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_hired` DATE NOT NULL,
  `dep_num` INT NOT NULL,
  `id_card` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC) VISIBLE,
  INDEX `fk_Staff_Department_dep_num_idx` (`dep_num` ASC) VISIBLE,
  CONSTRAINT `fk_Staff_Department_dep_num`
    FOREIGN KEY (`dep_num`)
    REFERENCES `cosc457`.`Department_christian` (`dep_num`),
  CONSTRAINT `fk_Staff_Id_id`
    FOREIGN KEY (`id_card`)
    REFERENCES `cosc457`.`Id_christian` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Department_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Department_christian` (
  `dep_num` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `office_num` VARCHAR(45) NOT NULL,
  `office_phone` VARCHAR(12) NOT NULL,
  `advisor_id` INT NOT NULL,
  PRIMARY KEY (`dep_num`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Department_Staff_id_idx` (`advisor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Staff_id`
    FOREIGN KEY (`advisor_id`)
    REFERENCES `cosc457`.`Staff_christian` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Course_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Course_christian` (
  `code` VARCHAR(8) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL DEFAULT 'This course has no description.',
  `dep_num` INT NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `id_UNIQUE` (`code` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `fk_Course_Department_dep_num_idx` (`dep_num` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Department_dep_num`
    FOREIGN KEY (`dep_num`)
    REFERENCES `cosc457`.`Department_christian` (`dep_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Program_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Program_christian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `is_degree_program` TINYINT NOT NULL DEFAULT '1',
  `dep_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Program_Department_dep_num_idx` (`dep_num` ASC) VISIBLE,
  CONSTRAINT `fk_Program_Department_dep_num`
    FOREIGN KEY (`dep_num`)
    REFERENCES `cosc457`.`Department_christian` (`dep_num`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Program_Courses_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Program_Courses_christian` (
  `program_id` INT NOT NULL,
  `course_code` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`program_id`, `course_code`),
  INDEX `fk_Program_Courses_Course_code_idx` (`course_code` ASC) VISIBLE,
  CONSTRAINT `fk_Program_Courses_Course_code`
    FOREIGN KEY (`course_code`)
    REFERENCES `cosc457`.`Course_christian` (`code`),
  CONSTRAINT `fk_Program_Courses_Program_id`
    FOREIGN KEY (`program_id`)
    REFERENCES `cosc457`.`Program_christian` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Student_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Student_christian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ssn` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_home` VARCHAR(12) NOT NULL,
  `phone_work` VARCHAR(12) NULL DEFAULT NULL,
  `citizenship_status` VARCHAR(45) NOT NULL,
  `grant_status` VARCHAR(45) NOT NULL DEFAULT 'None',
  `advisor_id` INT NOT NULL,
  `id_card` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC) VISIBLE,
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC) VISIBLE,
  INDEX `fk_Student_Staff_id_idx` (`advisor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Id_id`
    FOREIGN KEY (`id_card`)
    REFERENCES `cosc457`.`Id_christian` (`id`),
  CONSTRAINT `fk_Student_Staff_id`
    FOREIGN KEY (`advisor_id`)
    REFERENCES `cosc457`.`Staff_christian` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Program_Enrollment_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Program_Enrollment_christian` (
  `student_id` INT NOT NULL,
  `program_id` INT NOT NULL,
  `completed` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`student_id`, `program_id`),
  INDEX `fk_Program_Enrollment_Program_id_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_Program_Enrollment_Program_id`
    FOREIGN KEY (`program_id`)
    REFERENCES `cosc457`.`Program_christian` (`id`),
  CONSTRAINT `fk_Program_Enrollment_Student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `cosc457`.`Student_christian` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Section_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Section_christian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(8) NOT NULL,
  `num` VARCHAR(3) NOT NULL,
  `date_start` DATE NULL DEFAULT NULL,
  `date_end` DATE NULL DEFAULT NULL,
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Section_Staff_id_idx` (`instructor_id` ASC) VISIBLE,
  INDEX `fk_Section_Course_code_idx` (`course_code` ASC) VISIBLE,
  CONSTRAINT `fk_Section_Course_code`
    FOREIGN KEY (`course_code`)
    REFERENCES `cosc457`.`Course_christian` (`code`),
  CONSTRAINT `fk_Section_Staff_id`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `cosc457`.`Staff_christian` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cosc457`.`Student_Sections_christian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosc457`.`Student_Sections_christian` (
  `student_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'enrolled',
  `grade` VARCHAR(1) NULL DEFAULT NULL,
  `date_enrolled` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_completed` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`, `section_id`),
  INDEX `fk_Student_Sections_Section_id_idx` (`section_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Sections_Section_id`
    FOREIGN KEY (`section_id`)
    REFERENCES `cosc457`.`Section_christian` (`id`),
  CONSTRAINT `fk_Student_Sections_Student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `cosc457`.`Student_christian` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'status: \'registered\', \'enrolled\', \'withdrawn\', \'dropped\', \'passed\', \'failed\'';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
